import { prepareWebDemoData } from './geo/WebDemoData';
import {
  Customer,
  Driver,
  Facility,
  Incident,
  Order,
  CatalogItem,
  Promotion,
  Reward,
  RewardRedemption,
  PointsLedgerEntry,
  AuditLog,
  SystemSettings,
  User,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'USR-001',
    name: 'Carlos Mendoza',
    email: 'admin@laundryweb.com',
    role: 'ADMIN',
    avatar: '',
    facilityId: 'FAC-01',
  },
  {
    id: 'USR-002',
    name: 'Elena Rostova',
    email: 'supervisor@laundryweb.com',
    role: 'SUPERVISOR',
    avatar: '',
    facilityId: 'FAC-01',
  },
];

export const INITIAL_SETTINGS: SystemSettings = {
  maxOrdersPerDriver: 5,
  slaPickupMinutes: 45,
  slaDeliveryHours: 24,
  defaultFacilityId: 'FAC-01',
  currency: 'USD',
  currencySymbol: '$',
  timezone: 'America/Lima (UTC-5)',
  locale: 'es-PE',
  defaultCity: 'Metropolitana',
  phoneCountryCode: '+51',
  quarantineNotifySupervisor: true,
  autoSuggestDrivers: true,
};

export const INITIAL_FACILITIES: Facility[] = [
  {
    id: 'FAC-01',
    name: 'Sede Central Norte - Clean Hub',
    code: 'HUB-NORTE',
    address: 'Av. Industrial 1420, Parque Empresarial',
    city: 'Metropolitana',
    zone: 'Zona Norte & Centro',
    capacityMaxKgDay: 1500,
    currentLoadKgDay: 1140,
    activeOrders: 28,
    assignedDriversCount: 5,
    status: 'ACTIVE',
    phone: '+51 1 555-0192',
    managerName: 'Roberto Gómez',
    coordinates: { lat: -12.0464, lng: -77.0428 },
  },
  {
    id: 'FAC-02',
    name: 'Sede Fresh Miraflores',
    code: 'HUB-SUR',
    address: 'Calle Las Acacias 380, San Antonio',
    city: 'Metropolitana',
    zone: 'Zona Sur & Bahía',
    capacityMaxKgDay: 900,
    currentLoadKgDay: 780,
    activeOrders: 19,
    assignedDriversCount: 3,
    status: 'ACTIVE',
    phone: '+51 1 555-0844',
    managerName: 'Mariana Silva',
    coordinates: { lat: -12.1219, lng: -77.0297 },
  },
  {
    id: 'FAC-03',
    name: 'Sede San Isidro Executive',
    code: 'HUB-FINANCIERO',
    address: 'Av. Camino Real 720, Edificio Platinum',
    city: 'Metropolitana',
    zone: 'Zona Financiera & Residencial',
    capacityMaxKgDay: 600,
    currentLoadKgDay: 410,
    activeOrders: 12,
    assignedDriversCount: 2,
    status: 'ACTIVE',
    phone: '+51 1 555-0371',
    managerName: 'Daniel Benavides',
    coordinates: { lat: -12.0969, lng: -77.0353 },
  },
];

export const INITIAL_DRIVERS: Driver[] = [
  {
    id: 'DRV-101',
    name: 'Carlos Ruiz',
    phone: '+51 987 654 321',
    email: 'carlos.ruiz@laundryweb.com',
    avatar: '',
    vehicleType: 'VAN',
    vehiclePlate: 'ABC-123',
    facilityId: 'FAC-01',
    facilityName: 'Sede Central Norte - Clean Hub',
    zoneId: 'ZONA-NORTE',
    zoneName: 'Zona Norte & Centro',
    status: 'AVAILABLE',
    activeOrders: 2,
    maxOrders: 5,
    rating: 4.9,
    completedTripsToday: 8,
    location: {
      lat: -12.052,
      lng: -77.039,
      address: 'Cerca a Av. Colonial km 2.4',
      lastUpdated: 'Hace 3 min',
    },
  },
  {
    id: 'DRV-102',
    name: 'Mateo Quispe',
    phone: '+51 981 123 456',
    email: 'mateo.quispe@laundryweb.com',
    avatar: '',
    vehicleType: 'VAN',
    vehiclePlate: 'XYZ-789',
    facilityId: 'FAC-02',
    facilityName: 'Sede Fresh Miraflores',
    zoneId: 'ZONA-SUR',
    zoneName: 'Zona Sur & Bahía',
    status: 'AVAILABLE',
    activeOrders: 4,
    maxOrders: 5,
    rating: 4.8,
    completedTripsToday: 6,
    location: {
      lat: -12.115,
      lng: -77.032,
      address: 'En ruta: Av. Pardo con Comandante Espinar',
      lastUpdated: 'Hace 1 min',
    },
  },
  {
    id: 'DRV-103',
    name: 'Javier Arriola',
    phone: '+51 992 445 566',
    email: 'javier.arriola@laundryweb.com',
    avatar: '',
    vehicleType: 'MOTO',
    vehiclePlate: 'MOT-442',
    facilityId: 'FAC-03',
    facilityName: 'Sede San Isidro Executive',
    zoneId: 'ZONA-FINANCIERA',
    zoneName: 'Zona Financiera & Residencial',
    status: 'AVAILABLE',
    activeOrders: 1,
    maxOrders: 4,
    rating: 4.95,
    completedTripsToday: 11,
    location: {
      lat: -12.095,
      lng: -77.031,
      address: 'Calle Los Cedros 210',
      lastUpdated: 'Hace 5 min',
    },
  },
  {
    id: 'DRV-104',
    name: 'Andrea Morales',
    phone: '+51 976 889 900',
    email: 'andrea.morales@laundryweb.com',
    avatar: '',
    vehicleType: 'VAN',
    vehiclePlate: 'VWT-505',
    facilityId: 'FAC-01',
    facilityName: 'Sede Central Norte - Clean Hub',
    zoneId: 'ZONA-NORTE',
    zoneName: 'Zona Norte & Centro',
    status: 'ON_SERVICE',
    activeOrders: 5,
    maxOrders: 5,
    rating: 4.7,
    completedTripsToday: 7,
    location: {
      lat: -12.061,
      lng: -77.045,
      address: 'Entregando en Jr. Zorritos 490',
      lastUpdated: 'Hace 2 min',
    },
  },
  {
    id: 'DRV-105',
    name: 'Diego Valdivia',
    phone: '+51 965 334 221',
    email: 'diego.valdivia@laundryweb.com',
    avatar: '',
    vehicleType: 'CAMIONETA',
    vehiclePlate: 'PKU-881',
    facilityId: 'FAC-02',
    facilityName: 'Sede Fresh Miraflores',
    zoneId: 'ZONA-SUR',
    zoneName: 'Zona Sur & Bahía',
    status: 'AVAILABLE',
    activeOrders: 0,
    maxOrders: 5,
    rating: 4.85,
    completedTripsToday: 5,
    location: {
      lat: -12.13,
      lng: -77.022,
      address: 'Base Miraflores - En espera',
      lastUpdated: 'Hace 7 min',
    },
  },
  {
    id: 'DRV-106',
    name: 'Lucía Santillán',
    phone: '+51 944 112 887',
    email: 'lucia.santillan@laundryweb.com',
    avatar: '',
    vehicleType: 'VAN',
    vehiclePlate: 'ECO-204',
    facilityId: 'FAC-03',
    facilityName: 'Sede San Isidro Executive',
    zoneId: 'ZONA-FINANCIERA',
    zoneName: 'Zona Financiera & Residencial',
    status: 'AVAILABLE',
    activeOrders: 2,
    maxOrders: 5,
    rating: 4.92,
    completedTripsToday: 9,
    location: {
      lat: -12.091,
      lng: -77.04,
      address: 'Av. Prescott 330',
      lastUpdated: 'Hace 4 min',
    },
  },
  {
    id: 'DRV-107',
    name: 'Fernando Castro',
    phone: '+51 955 776 332',
    email: 'fernando.castro@laundryweb.com',
    avatar: '',
    vehicleType: 'MOTO',
    vehiclePlate: 'MOT-991',
    facilityId: 'FAC-01',
    facilityName: 'Sede Central Norte - Clean Hub',
    zoneId: 'ZONA-NORTE',
    zoneName: 'Zona Norte & Centro',
    status: 'OFFLINE',
    activeOrders: 0,
    maxOrders: 4,
    rating: 4.65,
    completedTripsToday: 3,
    location: {
      lat: -12.046,
      lng: -77.042,
      address: 'En mantenimiento vehicular',
      lastUpdated: 'Hace 45 min',
    },
  },
  {
    id: 'DRV-108',
    name: 'Gabriel Zúñiga',
    phone: '+51 933 221 445',
    email: 'gabriel.zuniga@laundryweb.com',
    avatar: '',
    vehicleType: 'VAN',
    vehiclePlate: 'FST-319',
    facilityId: 'FAC-02',
    facilityName: 'Sede Fresh Miraflores',
    zoneId: 'ZONA-SUR',
    zoneName: 'Zona Sur & Bahía',
    status: 'AVAILABLE',
    activeOrders: 3,
    maxOrders: 5,
    rating: 4.88,
    completedTripsToday: 8,
    location: {
      lat: -12.126,
      lng: -77.026,
      address: 'Malecón Balta 410',
      lastUpdated: 'Hace 2 min',
    },
  },
];

export const INITIAL_CUSTOMERS: Customer[] = [
  {
    id: 'CUST-001',
    fullName: 'María Torres Alarcón',
    email: 'maria.torres@gmail.com',
    phone: '+51 998 712 345',
    documentType: 'DNI',
    documentNumber: '47890123',
    kycStatus: 'APPROVED',
    kycReviewedAt: '2026-09-15 10:20',
    kycReviewedBy: 'Carlos Mendoza',
    kycDocumentUrl: '',
    kycSelfieUrl: '',
    addresses: [
      {
        street: 'Calle Grimaldo del Solar',
        number: '240',
        complement: 'Dpto 502',
        neighborhood: 'Miraflores',
        city: 'Metropolitana',
        reference: 'Frente al parque Reducto',
        coordinates: { lat: -12.1245, lng: -77.0241 },
      },
    ],
    membership: 'PREMIUM_FRESH',
    walletBalance: 84.5,
    points: 1240,
    activePromotionsCount: 2,
    totalOrders: 14,
    completedOrders: 13,
    createdAt: '2026-06-10',
    notes: 'Cliente preferente. Requiere entrega en horario vespertino.',
  },
  {
    id: 'CUST-002',
    fullName: 'Clínica San Gabriel S.A.',
    email: 'logistica@clinicasangabriel.com',
    phone: '+51 1 614 2200',
    documentType: 'RUT',
    documentNumber: '20554901823',
    kycStatus: 'APPROVED',
    kycReviewedAt: '2026-08-01 14:00',
    kycReviewedBy: 'Carlos Mendoza',
    kycDocumentUrl: '',
    kycSelfieUrl: '',
    addresses: [
      {
        street: 'Av. La Marina',
        number: '2955',
        complement: 'Área de Hospitalización',
        neighborhood: 'San Miguel',
        city: 'Metropolitana',
        reference: 'Puerta 3 de Carga',
        coordinates: { lat: -12.0789, lng: -77.0912 },
      },
    ],
    membership: 'CORPORATIVO',
    walletBalance: 650.0,
    points: 8900,
    activePromotionsCount: 1,
    totalOrders: 42,
    completedOrders: 39,
    createdAt: '2026-03-12',
    notes:
      'Cuenta B2B: uniformes médicos y sábanas de clínica con protocolo de sanitización extrema.',
  },
  {
    id: 'CUST-003',
    fullName: 'Andrés Villalobos Peña',
    email: 'andres.villa@techcorp.io',
    phone: '+51 981 405 889',
    documentType: 'DNI',
    documentNumber: '71239845',
    kycStatus: 'PENDING',
    kycSubmittedAt: '2026-09-29 09:15',
    kycDocumentUrl: '',
    kycSelfieUrl: '',
    addresses: [
      {
        street: 'Av. Javier Prado Oeste',
        number: '1850',
        complement: 'Piso 14 - A',
        neighborhood: 'San Isidro',
        city: 'Metropolitana',
        reference: 'Torre Empresarial Sigma',
        coordinates: { lat: -12.0911, lng: -77.0512 },
      },
    ],
    membership: 'ESTANDAR',
    walletBalance: 0.0,
    points: 150,
    activePromotionsCount: 1,
    totalOrders: 1,
    completedOrders: 0,
    createdAt: '2026-09-29',
    notes:
      'Nuevo registro. Pendiente de verificación documental KYC para desbloquear pedidos de alto volumen.',
  },
  {
    id: 'CUST-004',
    fullName: 'Luciana Barandiarán',
    email: 'luciana.b@estilourbano.pe',
    phone: '+51 945 667 112',
    documentType: 'DNI',
    documentNumber: '46389201',
    kycStatus: 'APPROVED',
    kycReviewedAt: '2026-07-22 11:30',
    kycReviewedBy: 'Elena Rostova',
    kycDocumentUrl: '',
    kycSelfieUrl: '',
    addresses: [
      {
        street: 'Malecón de la Reserva',
        number: '725',
        complement: 'Penthouse 12',
        neighborhood: 'Miraflores',
        city: 'Metropolitana',
        reference: 'Cerca a Larcomar',
        coordinates: { lat: -12.1312, lng: -77.0289 },
      },
    ],
    membership: 'ECO_WASH',
    walletBalance: 120.0,
    points: 2350,
    activePromotionsCount: 3,
    totalOrders: 19,
    completedOrders: 18,
    createdAt: '2026-05-18',
    notes:
      'Prefiere detergentes ecológicos biodegradables y bolsas de tela reutilizables.',
  },
  {
    id: 'CUST-005',
    fullName: 'Jorge Rospigliosi Soto',
    email: 'jorge.rospigliosi@outlook.com',
    phone: '+51 955 332 118',
    documentType: 'DNI',
    documentNumber: '09812457',
    kycStatus: 'REJECTED',
    kycSubmittedAt: '2026-09-28 16:40',
    kycReviewedAt: '2026-09-28 17:15',
    kycReviewedBy: 'Carlos Mendoza',
    kycRejectionReason:
      'La foto del documento de identidad no es legible y los bordes están recortados.',
    kycDocumentUrl: '',
    kycSelfieUrl: '',
    addresses: [
      {
        street: 'Av. Salaverry',
        number: '3100',
        complement: 'Dpto 301',
        neighborhood: 'San Isidro',
        city: 'Metropolitana',
        reference: 'Frente al Real Plaza Salaverry',
        coordinates: { lat: -12.0935, lng: -77.0543 },
      },
    ],
    membership: 'ESTANDAR',
    walletBalance: 15.0,
    points: 210,
    activePromotionsCount: 0,
    totalOrders: 3,
    completedOrders: 2,
    createdAt: '2026-08-14',
    notes: 'Reenvió nueva documentación por correo.',
  },
  {
    id: 'CUST-006',
    fullName: 'Sofía Montalvo Cisneros',
    email: 'sofia.montalvo@atelier.com',
    phone: '+51 977 443 190',
    documentType: 'DNI',
    documentNumber: '73901244',
    kycStatus: 'PENDING',
    kycSubmittedAt: '2026-09-29 14:02',
    kycDocumentUrl: '',
    kycSelfieUrl: '',
    addresses: [
      {
        street: 'Calle Dos de Mayo',
        number: '560',
        complement: 'Casa 2',
        neighborhood: 'San Isidro',
        city: 'Metropolitana',
        reference: 'A 2 cuadras de Av. Arequipa',
        coordinates: { lat: -12.1012, lng: -77.0345 },
      },
    ],
    membership: 'PREMIUM_FRESH',
    walletBalance: 45.0,
    points: 820,
    activePromotionsCount: 2,
    totalOrders: 7,
    completedOrders: 6,
    createdAt: '2026-07-04',
    notes:
      'Atelier de diseño textil. Envía prendas de seda y lino con frecuencia.',
  },
  {
    id: 'CUST-007',
    fullName: 'Hotel Boutique Casa Andina Fresh',
    email: 'operaciones@casaandinafresh.com',
    phone: '+51 1 445 9900',
    documentType: 'RUT',
    documentNumber: '20498112349',
    kycStatus: 'APPROVED',
    kycReviewedAt: '2026-05-10 09:00',
    kycReviewedBy: 'Carlos Mendoza',
    addresses: [
      {
        street: 'Av. Grau',
        number: '120',
        complement: 'Recepción Central',
        neighborhood: 'Barranco',
        city: 'Metropolitana',
        reference: 'Cerca al Puente de los Suspiros',
        coordinates: { lat: -12.1489, lng: -77.0212 },
      },
    ],
    membership: 'CORPORATIVO',
    walletBalance: 980.0,
    points: 15400,
    activePromotionsCount: 2,
    totalOrders: 64,
    completedOrders: 61,
    createdAt: '2026-02-19',
    notes: 'Entrega diaria de blancos y mantelería fina.',
  },
  {
    id: 'CUST-008',
    fullName: 'Renzo Cavagnaro Rossi',
    email: 'renzo.c@legalgroup.pe',
    phone: '+51 993 881 229',
    documentType: 'DNI',
    documentNumber: '41908233',
    kycStatus: 'APPROVED',
    kycReviewedAt: '2026-08-19 16:10',
    kycReviewedBy: 'Elena Rostova',
    addresses: [
      {
        street: 'Calle Los Pinos',
        number: '180',
        complement: 'Oficina 604',
        neighborhood: 'Miraflores',
        city: 'Metropolitana',
        reference: 'Entre Benavides y Schell',
        coordinates: { lat: -12.1223, lng: -77.0298 },
      },
    ],
    membership: 'PREMIUM_FRESH',
    walletBalance: 60.0,
    points: 980,
    activePromotionsCount: 1,
    totalOrders: 9,
    completedOrders: 8,
    createdAt: '2026-06-25',
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'SOL-4587',
    trackingNumber: 'LW-TRK-4587-PE',
    customerId: 'CUST-001',
    customerName: 'María Torres Alarcón',
    customerPhone: '+51 998 712 345',
    customerEmail: 'maria.torres@gmail.com',
    customerPlan: 'Premium Fresh',
    customerAddress: {
      street: 'Calle Grimaldo del Solar',
      number: '240',
      complement: 'Dpto 502',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      reference: 'Frente al parque Reducto',
      coordinates: { lat: -12.1245, lng: -77.0241 },
    },
    deliveryAddress: {
      street: 'Calle Grimaldo del Solar',
      number: '240',
      complement: 'Dpto 502',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      reference: 'Frente al parque Reducto',
      coordinates: { lat: -12.1245, lng: -77.0241 },
    },
    facilityId: 'FAC-02',
    facilityName: 'Sede Fresh Miraflores',
    zoneId: 'ZONA-SUR',
    zoneName: 'Zona Sur & Bahía',
    priority: 'URGENT',
    status: 'PICKUP_PENDING',
    slaStatus: 'ATTENTION',
    slaDeadline: 'Hoy 18:30',
    slaProgressPercent: 65,
    items: [
      {
        id: 'ITM-01',
        name: 'Traje ejecutivo 2 piezas',
        quantity: 2,
        unitPrice: 18.0,
        category: 'PRENDAS',
        notes: 'Cuidado con botones de nácar',
      },
      {
        id: 'ITM-02',
        name: 'Camisas de algodón egipcio',
        quantity: 5,
        unitPrice: 7.0,
        category: 'PRENDAS',
        notes: 'Almidonado ligero',
      },
      {
        id: 'ITM-03',
        name: 'Vestido de fiesta de seda',
        quantity: 1,
        unitPrice: 26.0,
        category: 'DELICADOS',
        notes: 'Dry cleaning ecológico',
      },
    ],
    itemCount: 8,
    serviceType: 'Lavado + Dry Cleaning Premium',
    extras: [
      { id: 'EXT-01', name: 'Almidonado suave cuellos', price: 4.0 },
      { id: 'EXT-02', name: 'Protector textil antiarrugas', price: 6.0 },
    ],
    pricing: {
      subtotal: 97.0,
      discount: 15.0,
      extrasTotal: 10.0,
      deliveryFee: 0.0,
      total: 92.0,
      currency: 'USD',
      promoCodeApplied: 'FRESHSTART',
      paymentMethod: 'TARJETA',
      paymentStatus: 'PAID',
    },
    pickup: {
      date: 'Hoy',
      timeSlot: '16:00 - 18:00',
      notes: 'Portería avisa al intercomunicador 502.',
    },
    delivery: {
      targetDate: 'Mañana',
      timeSlot: '10:00 - 12:00',
      recipientName: 'María Torres Alarcón',
      recipientPhone: '+51 998 712 345',
      notes: 'Entrega en perchas biodegradables.',
    },
    incidentsCount: 0,
    timeline: [
      {
        id: 'TL-01',
        status: 'CREATED',
        label: 'Solicitud creada en plataforma',
        timestamp: 'Hoy 14:15',
        userName: 'María Torres Alarcón',
        userRole: 'ADMIN',
        notes: 'Generada vía Web Portal',
      },
      {
        id: 'TL-02',
        status: 'PICKUP_PENDING',
        label: 'Esperando asignación de chofer',
        timestamp: 'Hoy 14:16',
        userName: 'Sistema LaundryWeb',
        userRole: 'ADMIN',
        notes: 'Enrutado a Sede Fresh Miraflores',
      },
    ],
    createdAt: '2026-09-29 14:15',
    updatedAt: '2026-09-29 14:16',
  },
  {
    id: 'SOL-4584',
    trackingNumber: 'LW-TRK-4584-PE',
    customerId: 'CUST-002',
    customerName: 'Clínica San Gabriel S.A.',
    customerPhone: '+51 1 614 2200',
    customerEmail: 'logistica@clinicasangabriel.com',
    customerPlan: 'Corporativo',
    customerAddress: {
      street: 'Av. La Marina',
      number: '2955',
      complement: 'Área de Hospitalización',
      neighborhood: 'San Miguel',
      city: 'Metropolitana',
      reference: 'Puerta 3 de Carga',
      coordinates: { lat: -12.0789, lng: -77.0912 },
    },
    deliveryAddress: {
      street: 'Av. La Marina',
      number: '2955',
      complement: 'Área de Hospitalización',
      neighborhood: 'San Miguel',
      city: 'Metropolitana',
      reference: 'Puerta 3 de Carga',
      coordinates: { lat: -12.0789, lng: -77.0912 },
    },
    facilityId: 'FAC-01',
    facilityName: 'Sede Central Norte - Clean Hub',
    zoneId: 'ZONA-NORTE',
    zoneName: 'Zona Norte & Centro',
    priority: 'HIGH',
    status: 'IN_PROCESS',
    slaStatus: 'ON_TIME',
    slaDeadline: 'Hoy 20:00',
    slaProgressPercent: 40,
    items: [
      {
        id: 'ITM-11',
        name: 'Uniformes médicos quirúrgicos (Lote A)',
        quantity: 140,
        unitPrice: 2.2,
        category: 'INDUSTRIAL',
      },
      {
        id: 'ITM-12',
        name: 'Sábanas hospitalarias antibacteriales',
        quantity: 80,
        unitPrice: 3.0,
        category: 'INDUSTRIAL',
      },
    ],
    itemCount: 220,
    serviceType: 'Sanitización Hospitalaria Termodesinfectante',
    extras: [
      { id: 'EXT-10', name: 'Certificado de Sanitización Ozono', price: 25.0 },
    ],
    pricing: {
      subtotal: 548.0,
      discount: 50.0,
      extrasTotal: 25.0,
      deliveryFee: 0.0,
      total: 523.0,
      currency: 'USD',
      paymentMethod: 'TRANSFERENCIA',
      paymentStatus: 'PAID',
    },
    pickup: {
      date: 'Hoy',
      timeSlot: '08:00 - 09:30',
      driverId: 'DRV-101',
      driverName: 'Carlos Ruiz',
      vehiclePlate: 'ABC-123',
      completedAt: 'Hoy 09:12',
    },
    delivery: {
      targetDate: 'Hoy',
      timeSlot: '19:00 - 21:00',
      recipientName: 'Dr. Víctor Arana - Almacén',
      recipientPhone: '+51 1 614 2201',
    },
    incidentsCount: 0,
    timeline: [
      {
        id: 'TL-10',
        status: 'CREATED',
        label: 'Solicitud corporativa emitida',
        timestamp: 'Hoy 07:30',
        userName: 'Clínica San Gabriel',
        userRole: 'ADMIN',
      },
      {
        id: 'TL-11',
        status: 'PICKUP_ASSIGNED',
        label: 'Chofer asignado para recogida',
        timestamp: 'Hoy 07:45',
        userName: 'Elena Rostova',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-12',
        status: 'PICKED_UP',
        label: 'Carga recogida en almacén hospitalario',
        timestamp: 'Hoy 09:12',
        userName: 'Carlos Ruiz',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-13',
        status: 'AT_FACILITY',
        label: 'Recepción en planta e ingreso a túnel de lavado',
        timestamp: 'Hoy 10:05',
        userName: 'Roberto Gómez',
        userRole: 'ADMIN',
      },
      {
        id: 'TL-14',
        status: 'IN_PROCESS',
        label: 'Ciclo termodesinfectante en curso (60%)',
        timestamp: 'Hoy 11:30',
        userName: 'Roberto Gómez',
        userRole: 'ADMIN',
      },
    ],
    createdAt: '2026-09-29 07:30',
    updatedAt: '2026-09-29 11:30',
  },
  {
    id: 'SOL-4579',
    trackingNumber: 'LW-TRK-4579-PE',
    customerId: 'CUST-004',
    customerName: 'Luciana Barandiarán',
    customerPhone: '+51 945 667 112',
    customerEmail: 'luciana.b@estilourbano.pe',
    customerPlan: 'Eco Wash Club',
    customerAddress: {
      street: 'Malecón de la Reserva',
      number: '725',
      complement: 'Penthouse 12',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      coordinates: { lat: -12.1312, lng: -77.0289 },
    },
    deliveryAddress: {
      street: 'Malecón de la Reserva',
      number: '725',
      complement: 'Penthouse 12',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      coordinates: { lat: -12.1312, lng: -77.0289 },
    },
    facilityId: 'FAC-02',
    facilityName: 'Sede Fresh Miraflores',
    zoneId: 'ZONA-SUR',
    zoneName: 'Zona Sur & Bahía',
    priority: 'HIGH',
    status: 'QUARANTINE',
    slaStatus: 'AT_RISK',
    slaDeadline: 'Hoy 17:00',
    slaProgressPercent: 88,
    quarantineReason: 'Mancha rebelde desconocida en vestido de diseñador',
    quarantineNotes:
      'Presenta decoloración química previa en orla inferior. Requiere autorización del cliente antes de aplicar solvente enzimático.',
    quarantineDate: 'Hoy 11:15',
    items: [
      {
        id: 'ITM-21',
        name: 'Vestido Haute Couture estampado',
        quantity: 1,
        unitPrice: 38.0,
        category: 'DELICADOS',
        notes: 'Prenda delicada de lino y viscosa',
      },
      {
        id: 'ITM-22',
        name: 'Pantalón palazzo marfil',
        quantity: 2,
        unitPrice: 12.0,
        category: 'PRENDAS',
      },
    ],
    itemCount: 3,
    serviceType: 'Eco Dry Clean & Restauración Fina',
    extras: [{ id: 'EXT-20', name: 'Bolsas compostables de maíz', price: 3.5 }],
    pricing: {
      subtotal: 62.0,
      discount: 0.0,
      extrasTotal: 3.5,
      deliveryFee: 0.0,
      total: 65.5,
      currency: 'USD',
      paymentMethod: 'TARJETA',
      paymentStatus: 'PAID',
    },
    pickup: {
      date: 'Hoy',
      timeSlot: '09:00 - 10:30',
      driverId: 'DRV-102',
      driverName: 'Mateo Quispe',
      completedAt: 'Hoy 09:48',
    },
    delivery: {
      targetDate: 'Hoy',
      timeSlot: '17:00 - 19:00',
      recipientName: 'Luciana Barandiarán',
      recipientPhone: '+51 945 667 112',
    },
    incidentsCount: 1,
    timeline: [
      {
        id: 'TL-20',
        status: 'CREATED',
        label: 'Solicitud creada',
        timestamp: 'Hoy 08:10',
        userName: 'Luciana Barandiarán',
        userRole: 'ADMIN',
      },
      {
        id: 'TL-21',
        status: 'PICKED_UP',
        label: 'Recogido por chofer Mateo Quispe',
        timestamp: 'Hoy 09:48',
        userName: 'Mateo Quispe',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-22',
        status: 'AT_FACILITY',
        label: 'Ingresado a Sede Miraflores',
        timestamp: 'Hoy 10:20',
        userName: 'Mariana Silva',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-23',
        status: 'QUARANTINE',
        label: 'Puesto en INSCIDENCIA por inspección técnica',
        timestamp: 'Hoy 11:15',
        userName: 'Mariana Silva',
        userRole: 'SUPERVISOR',
        notes: 'Mancha química persistente detectada',
      },
    ],
    createdAt: '2026-09-29 08:10',
    updatedAt: '2026-09-29 11:15',
  },
  {
    id: 'SOL-4580',
    trackingNumber: 'LW-TRK-4580-PE',
    customerId: 'CUST-007',
    customerName: 'Hotel Boutique Casa Andina Fresh',
    customerPhone: '+51 1 445 9900',
    customerEmail: 'operaciones@casaandinafresh.com',
    customerPlan: 'Corporativo',
    customerAddress: {
      street: 'Av. Grau',
      number: '120',
      complement: 'Recepción Central',
      neighborhood: 'Barranco',
      city: 'Metropolitana',
      coordinates: { lat: -12.1489, lng: -77.0212 },
    },
    deliveryAddress: {
      street: 'Av. Grau',
      number: '120',
      complement: 'Recepción Central',
      neighborhood: 'Barranco',
      city: 'Metropolitana',
      coordinates: { lat: -12.1489, lng: -77.0212 },
    },
    facilityId: 'FAC-02',
    facilityName: 'Sede Fresh Miraflores',
    zoneId: 'ZONA-SUR',
    zoneName: 'Zona Sur & Bahía',
    priority: 'HIGH',
    status: 'READY_FOR_DELIVERY',
    slaStatus: 'ON_TIME',
    slaDeadline: 'Hoy 19:30',
    slaProgressPercent: 50,
    items: [
      {
        id: 'ITM-31',
        name: 'Juegos de cama King Size 600 hilos',
        quantity: 25,
        unitPrice: 6.5,
        category: 'HOGAR',
      },
      {
        id: 'ITM-32',
        name: 'Mantelería blanca para banquetes',
        quantity: 40,
        unitPrice: 3.5,
        category: 'HOGAR',
      },
    ],
    itemCount: 65,
    serviceType: 'Lavado Hotelero y Planchado Calandra',
    extras: [],
    pricing: {
      subtotal: 302.5,
      discount: 30.0,
      extrasTotal: 0.0,
      deliveryFee: 0.0,
      total: 272.5,
      currency: 'USD',
      paymentMethod: 'TRANSFERENCIA',
      paymentStatus: 'PAID',
    },
    pickup: {
      date: 'Hoy',
      timeSlot: '07:00 - 08:30',
      driverId: 'DRV-102',
      driverName: 'Mateo Quispe',
      completedAt: 'Hoy 08:15',
    },
    delivery: {
      targetDate: 'Hoy',
      timeSlot: '17:00 - 18:30',
      recipientName: 'Conserjería Principal',
      recipientPhone: '+51 1 445 9900',
    },
    incidentsCount: 0,
    timeline: [
      {
        id: 'TL-30',
        status: 'CREATED',
        label: 'Solicitud programada diaria',
        timestamp: 'Hoy 06:45',
        userName: 'Hotel Boutique',
        userRole: 'ADMIN',
      },
      {
        id: 'TL-31',
        status: 'PICKED_UP',
        label: 'Recogido por Mateo Quispe',
        timestamp: 'Hoy 08:15',
        userName: 'Mateo Quispe',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-32',
        status: 'AT_FACILITY',
        label: 'Recepción en planta Miraflores',
        timestamp: 'Hoy 09:00',
        userName: 'Mariana Silva',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-33',
        status: 'IN_PROCESS',
        label: 'Procesamiento en lavadoras industriales',
        timestamp: 'Hoy 10:15',
        userName: 'Mariana Silva',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-34',
        status: 'QUALITY_CONTROL',
        label: 'Control de calidad aprobado sin manchas',
        timestamp: 'Hoy 12:40',
        userName: 'Mariana Silva',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-35',
        status: 'READY_FOR_DELIVERY',
        label: 'Empaquetado y listo para despacho de entrega',
        timestamp: 'Hoy 13:10',
        userName: 'Mariana Silva',
        userRole: 'SUPERVISOR',
      },
    ],
    createdAt: '2026-09-29 06:45',
    updatedAt: '2026-09-29 13:10',
  },
  {
    id: 'SOL-4575',
    trackingNumber: 'LW-TRK-4575-PE',
    customerId: 'CUST-008',
    customerName: 'Renzo Cavagnaro Rossi',
    customerPhone: '+51 993 881 229',
    customerEmail: 'renzo.c@legalgroup.pe',
    customerPlan: 'Premium Fresh',
    customerAddress: {
      street: 'Calle Los Pinos',
      number: '180',
      complement: 'Oficina 604',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      coordinates: { lat: -12.1223, lng: -77.0298 },
    },
    deliveryAddress: {
      street: 'Calle Los Pinos',
      number: '180',
      complement: 'Oficina 604',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      coordinates: { lat: -12.1223, lng: -77.0298 },
    },
    facilityId: 'FAC-03',
    facilityName: 'Sede San Isidro Executive',
    zoneId: 'ZONA-FINANCIERA',
    zoneName: 'Zona Financiera & Residencial',
    priority: 'NORMAL',
    status: 'OUT_FOR_DELIVERY',
    slaStatus: 'ON_TIME',
    slaDeadline: 'Hoy 17:30',
    slaProgressPercent: 70,
    items: [
      {
        id: 'ITM-41',
        name: 'Trajes de lana fría para corte',
        quantity: 3,
        unitPrice: 20.0,
        category: 'PRENDAS',
      },
      {
        id: 'ITM-42',
        name: 'Corbatas de seda italiana',
        quantity: 4,
        unitPrice: 6.0,
        category: 'DELICADOS',
      },
    ],
    itemCount: 7,
    serviceType: 'Dry Cleaning Ejecutivo + Planchado Vapor',
    extras: [{ id: 'EXT-40', name: 'Perchas de madera barnizada', price: 5.0 }],
    pricing: {
      subtotal: 84.0,
      discount: 10.0,
      extrasTotal: 5.0,
      deliveryFee: 0.0,
      total: 79.0,
      currency: 'USD',
      paymentMethod: 'TARJETA',
      paymentStatus: 'PAID',
    },
    pickup: {
      date: 'Ayer',
      timeSlot: '16:00 - 18:00',
      driverId: 'DRV-103',
      driverName: 'Javier Arriola',
      completedAt: 'Ayer 17:15',
    },
    delivery: {
      targetDate: 'Hoy',
      timeSlot: '15:00 - 17:00',
      driverId: 'DRV-103',
      driverName: 'Javier Arriola',
      vehiclePlate: 'MOT-442',
      recipientName: 'Renzo Cavagnaro',
      recipientPhone: '+51 993 881 229',
      scheduledAt: 'Hoy 14:00',
    },
    incidentsCount: 0,
    timeline: [
      {
        id: 'TL-40',
        status: 'DELIVERY_ASSIGNED',
        label: 'Asignado chofer de entrega Javier Arriola',
        timestamp: 'Hoy 14:05',
        userName: 'Elena Rostova',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-41',
        status: 'OUT_FOR_DELIVERY',
        label: 'En ruta de entrega hacia Calle Los Pinos',
        timestamp: 'Hoy 14:30',
        userName: 'Javier Arriola',
        userRole: 'SUPERVISOR',
      },
    ],
    createdAt: '2026-09-28 15:00',
    updatedAt: '2026-09-29 14:30',
  },
  {
    id: 'SOL-4560',
    trackingNumber: 'LW-TRK-4560-PE',
    customerId: 'CUST-006',
    customerName: 'Sofía Montalvo Cisneros',
    customerPhone: '+51 977 443 190',
    customerEmail: 'sofia.montalvo@atelier.com',
    customerPlan: 'Premium Fresh',
    customerAddress: {
      street: 'Calle Dos de Mayo',
      number: '560',
      complement: 'Casa 2',
      neighborhood: 'San Isidro',
      city: 'Metropolitana',
      coordinates: { lat: -12.1012, lng: -77.0345 },
    },
    deliveryAddress: {
      street: 'Calle Dos de Mayo',
      number: '560',
      complement: 'Casa 2',
      neighborhood: 'San Isidro',
      city: 'Metropolitana',
      coordinates: { lat: -12.1012, lng: -77.0345 },
    },
    facilityId: 'FAC-03',
    facilityName: 'Sede San Isidro Executive',
    zoneId: 'ZONA-FINANCIERA',
    zoneName: 'Zona Financiera & Residencial',
    priority: 'URGENT',
    status: 'PICKUP_PENDING',
    slaStatus: 'OVERDUE',
    slaDeadline: 'Hoy 14:00',
    slaProgressPercent: 100,
    items: [
      {
        id: 'ITM-51',
        name: 'Edredón de plumas Queen Size',
        quantity: 1,
        unitPrice: 28.0,
        category: 'HOGAR',
      },
      {
        id: 'ITM-52',
        name: 'Cortinas de terciopelo (pares)',
        quantity: 2,
        unitPrice: 22.0,
        category: 'HOGAR',
      },
    ],
    itemCount: 3,
    serviceType: 'Lavado al Seco Especializado Hogar',
    extras: [],
    pricing: {
      subtotal: 72.0,
      discount: 0.0,
      extrasTotal: 0.0,
      deliveryFee: 5.0,
      total: 77.0,
      currency: 'USD',
      paymentMethod: 'TARJETA',
      paymentStatus: 'PAID',
    },
    pickup: {
      date: 'Hoy',
      timeSlot: '12:00 - 14:00',
      notes: '¡URGENTE! Cliente viaja mañana temprano.',
    },
    delivery: {
      targetDate: 'Hoy',
      timeSlot: '20:00 - 22:00',
      recipientName: 'Sofía Montalvo',
      recipientPhone: '+51 977 443 190',
    },
    incidentsCount: 1,
    timeline: [
      {
        id: 'TL-50',
        status: 'CREATED',
        label: 'Solicitud creada con prioridad urgente',
        timestamp: 'Hoy 10:45',
        userName: 'Sofía Montalvo',
        userRole: 'ADMIN',
      },
      {
        id: 'TL-51',
        status: 'PICKUP_PENDING',
        label: 'Sin asignar chofer aún (demora logística)',
        timestamp: 'Hoy 10:46',
        userName: 'Sistema LaundryWeb',
        userRole: 'ADMIN',
      },
    ],
    createdAt: '2026-09-29 10:45',
    updatedAt: '2026-09-29 14:05',
  },
  {
    id: 'SOL-4552',
    trackingNumber: 'LW-TRK-4552-PE',
    customerId: 'CUST-001',
    customerName: 'María Torres Alarcón',
    customerPhone: '+51 998 712 345',
    customerEmail: 'maria.torres@gmail.com',
    customerPlan: 'Premium Fresh',
    customerAddress: {
      street: 'Calle Grimaldo del Solar',
      number: '240',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      coordinates: { lat: -12.1245, lng: -77.0241 },
    },
    deliveryAddress: {
      street: 'Calle Grimaldo del Solar',
      number: '240',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      coordinates: { lat: -12.1245, lng: -77.0241 },
    },
    facilityId: 'FAC-02',
    facilityName: 'Sede Fresh Miraflores',
    zoneId: 'ZONA-SUR',
    zoneName: 'Zona Sur & Bahía',
    priority: 'NORMAL',
    status: 'CLOSED',
    slaStatus: 'ON_TIME',
    slaDeadline: '2026-09-27',
    slaProgressPercent: 100,
    items: [
      {
        id: 'ITM-61',
        name: 'Prendas de uso diario (Bolsa 8kg)',
        quantity: 1,
        unitPrice: 24.0,
        category: 'PRENDAS',
      },
    ],
    itemCount: 1,
    serviceType: 'Lavado + Doblado Fresh Pack',
    extras: [],
    pricing: {
      subtotal: 24.0,
      discount: 4.0,
      extrasTotal: 0.0,
      deliveryFee: 0.0,
      total: 20.0,
      currency: 'USD',
      paymentMethod: 'BILLETERA',
      paymentStatus: 'PAID',
    },
    pickup: {
      date: '2026-09-26',
      timeSlot: '10:00 - 12:00',
      driverId: 'DRV-105',
      driverName: 'Diego Valdivia',
      completedAt: '2026-09-26 11:10',
    },
    delivery: {
      targetDate: '2026-09-27',
      timeSlot: '16:00 - 18:00',
      driverId: 'DRV-102',
      driverName: 'Mateo Quispe',
      completedAt: '2026-09-27 16:45',
      recipientName: 'María Torres',
      recipientPhone: '+51 998 712 345',
    },
    incidentsCount: 0,
    timeline: [
      {
        id: 'TL-60',
        status: 'DELIVERED',
        label: 'Entregado con conformidad del cliente',
        timestamp: '2026-09-27 16:45',
        userName: 'Mateo Quispe',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-61',
        status: 'CLOSED',
        label: 'Solicitud cerrada exitosamente',
        timestamp: '2026-09-27 17:00',
        userName: 'Elena Rostova',
        userRole: 'SUPERVISOR',
      },
    ],
    createdAt: '2026-09-26 09:00',
    updatedAt: '2026-09-27 17:00',
  },
  {
    id: 'SOL-4581',
    trackingNumber: 'LW-TRK-4581-PE',
    customerId: 'CUST-003',
    customerName: 'Andrés Villalobos Peña',
    customerPhone: '+51 981 405 889',
    customerEmail: 'andres.villa@techcorp.io',
    customerPlan: 'Estándar',
    customerAddress: {
      street: 'Av. Javier Prado Oeste',
      number: '1850',
      neighborhood: 'San Isidro',
      city: 'Metropolitana',
      coordinates: { lat: -12.0911, lng: -77.0512 },
    },
    deliveryAddress: {
      street: 'Av. Javier Prado Oeste',
      number: '1850',
      neighborhood: 'San Isidro',
      city: 'Metropolitana',
      coordinates: { lat: -12.0911, lng: -77.0512 },
    },
    facilityId: 'FAC-03',
    facilityName: 'Sede San Isidro Executive',
    zoneId: 'ZONA-FINANCIERA',
    zoneName: 'Zona Financiera & Residencial',
    priority: 'NORMAL',
    status: 'AT_FACILITY',
    slaStatus: 'ON_TIME',
    slaDeadline: 'Mañana 16:00',
    slaProgressPercent: 25,
    items: [
      {
        id: 'ITM-71',
        name: 'Camisas manga larga',
        quantity: 6,
        unitPrice: 6.5,
        category: 'PRENDAS',
      },
      {
        id: 'ITM-72',
        name: 'Pantalones de vestir',
        quantity: 3,
        unitPrice: 9.0,
        category: 'PRENDAS',
      },
    ],
    itemCount: 9,
    serviceType: 'Lavado y Planchado Ejecutivo',
    extras: [],
    pricing: {
      subtotal: 66.0,
      discount: 0.0,
      extrasTotal: 0.0,
      deliveryFee: 4.0,
      total: 70.0,
      currency: 'USD',
      paymentMethod: 'TARJETA',
      paymentStatus: 'PAID',
    },
    pickup: {
      date: 'Hoy',
      timeSlot: '11:00 - 13:00',
      driverId: 'DRV-106',
      driverName: 'Lucía Santillán',
      completedAt: 'Hoy 12:20',
    },
    delivery: {
      targetDate: 'Mañana',
      timeSlot: '14:00 - 16:00',
      recipientName: 'Andrés Villalobos',
      recipientPhone: '+51 981 405 889',
    },
    incidentsCount: 0,
    timeline: [
      {
        id: 'TL-70',
        status: 'PICKED_UP',
        label: 'Recogida realizada por Lucía Santillán',
        timestamp: 'Hoy 12:20',
        userName: 'Lucía Santillán',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-71',
        status: 'AT_FACILITY',
        label: 'Pesaje e ingreso a clasificación en planta San Isidro',
        timestamp: 'Hoy 13:05',
        userName: 'Daniel Benavides',
        userRole: 'SUPERVISOR',
      },
    ],
    createdAt: '2026-09-29 10:00',
    updatedAt: '2026-09-29 13:05',
  },
  {
    id: 'SOL-4582',
    trackingNumber: 'LW-TRK-4582-PE',
    customerId: 'CUST-004',
    customerName: 'Luciana Barandiarán',
    customerPhone: '+51 945 667 112',
    customerEmail: 'luciana.b@estilourbano.pe',
    customerPlan: 'Eco Wash Club',
    customerAddress: {
      street: 'Malecón de la Reserva',
      number: '725',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      coordinates: { lat: -12.1312, lng: -77.0289 },
    },
    deliveryAddress: {
      street: 'Malecón de la Reserva',
      number: '725',
      neighborhood: 'Miraflores',
      city: 'Metropolitana',
      coordinates: { lat: -12.1312, lng: -77.0289 },
    },
    facilityId: 'FAC-02',
    facilityName: 'Sede Fresh Miraflores',
    zoneId: 'ZONA-SUR',
    zoneName: 'Zona Sur & Bahía',
    priority: 'NORMAL',
    status: 'QUALITY_CONTROL',
    slaStatus: 'ON_TIME',
    slaDeadline: 'Hoy 19:00',
    slaProgressPercent: 55,
    items: [
      {
        id: 'ITM-81',
        name: 'Abrigo de lana alpaca',
        quantity: 1,
        unitPrice: 32.0,
        category: 'DELICADOS',
      },
      {
        id: 'ITM-82',
        name: 'Bufandas de cachemira',
        quantity: 2,
        unitPrice: 14.0,
        category: 'DELICADOS',
      },
    ],
    itemCount: 3,
    serviceType: 'Limpieza Ecológica Lana & Fibras Naturales',
    extras: [
      { id: 'EXT-80', name: 'Tratamiento antipolillas botánico', price: 8.0 },
    ],
    pricing: {
      subtotal: 60.0,
      discount: 0.0,
      extrasTotal: 8.0,
      deliveryFee: 0.0,
      total: 68.0,
      currency: 'USD',
      paymentMethod: 'TARJETA',
      paymentStatus: 'PAID',
    },
    pickup: {
      date: 'Hoy',
      timeSlot: '09:00 - 11:00',
      driverId: 'DRV-102',
      driverName: 'Mateo Quispe',
      completedAt: 'Hoy 10:10',
    },
    delivery: {
      targetDate: 'Hoy',
      timeSlot: '18:00 - 20:00',
      recipientName: 'Luciana Barandiarán',
      recipientPhone: '+51 945 667 112',
    },
    incidentsCount: 0,
    timeline: [
      {
        id: 'TL-80',
        status: 'IN_PROCESS',
        label: 'Limpieza con solvente bio completada',
        timestamp: 'Hoy 13:00',
        userName: 'Mariana Silva',
        userRole: 'SUPERVISOR',
      },
      {
        id: 'TL-81',
        status: 'QUALITY_CONTROL',
        label: 'Revisión minuciosa de fibras bajo lámpara de luz fría',
        timestamp: 'Hoy 14:10',
        userName: 'Mariana Silva',
        userRole: 'SUPERVISOR',
      },
    ],
    createdAt: '2026-09-29 08:30',
    updatedAt: '2026-09-29 14:10',
  },
  {
    id: 'SOL-4586',
    trackingNumber: 'LW-TRK-4586-PE',
    customerId: 'CUST-005',
    customerName: 'Jorge Rospigliosi Soto',
    customerPhone: '+51 955 332 118',
    customerEmail: 'jorge.rospigliosi@outlook.com',
    customerPlan: 'Estándar',
    customerAddress: {
      street: 'Av. Salaverry',
      number: '3100',
      neighborhood: 'San Isidro',
      city: 'Metropolitana',
      coordinates: { lat: -12.0935, lng: -77.0543 },
    },
    deliveryAddress: {
      street: 'Av. Salaverry',
      number: '3100',
      neighborhood: 'San Isidro',
      city: 'Metropolitana',
      coordinates: { lat: -12.0935, lng: -77.0543 },
    },
    facilityId: 'FAC-03',
    facilityName: 'Sede San Isidro Executive',
    zoneId: 'ZONA-FINANCIERA',
    zoneName: 'Zona Financiera & Residencial',
    priority: 'HIGH',
    status: 'PICKUP_ASSIGNED',
    slaStatus: 'ATTENTION',
    slaDeadline: 'Hoy 16:30',
    slaProgressPercent: 60,
    items: [
      {
        id: 'ITM-91',
        name: 'Sacos de paño fino',
        quantity: 2,
        unitPrice: 19.0,
        category: 'PRENDAS',
      },
    ],
    itemCount: 2,
    serviceType: 'Dry Cleaning Express',
    extras: [],
    pricing: {
      subtotal: 38.0,
      discount: 0.0,
      extrasTotal: 0.0,
      deliveryFee: 4.0,
      total: 42.0,
      currency: 'USD',
      paymentMethod: 'EFECTIVO',
      paymentStatus: 'PENDING',
    },
    pickup: {
      date: 'Hoy',
      timeSlot: '15:00 - 16:30',
      driverId: 'DRV-103',
      driverName: 'Javier Arriola',
      vehiclePlate: 'MOT-442',
      notes: 'Llamar al llegar.',
    },
    delivery: {
      targetDate: 'Mañana',
      timeSlot: '10:00 - 12:00',
      recipientName: 'Jorge Rospigliosi',
      recipientPhone: '+51 955 332 118',
    },
    incidentsCount: 0,
    timeline: [
      {
        id: 'TL-90',
        status: 'PICKUP_ASSIGNED',
        label: 'Asignado chofer Javier Arriola',
        timestamp: 'Hoy 14:00',
        userName: 'Elena Rostova',
        userRole: 'SUPERVISOR',
      },
    ],
    createdAt: '2026-09-29 13:45',
    updatedAt: '2026-09-29 14:00',
  },
];

export const INITIAL_INCIDENTS: Incident[] = [
  {
    id: 'INC-0187',
    orderId: 'SOL-4579',
    customerId: 'CUST-004',
    customerName: 'Luciana Barandiarán',
    type: 'MANCHA_PERSISTENTE',
    severity: 'ALTA',
    status: 'IN_PROGRESS',
    description:
      'Mancha rebelde desconocida en vestido de alta costura. Se detectó riesgo de desprendimiento de pigmento si se aplica percloroetileno estándar.',
    evidences: [
      {
        id: 'EVD-01',
        url: '',
        caption:
          'Detalle de la orla inferior del vestido con residuo químico previo',
        uploadedAt: '2026-09-29 11:15',
      },
    ],
    assignedTo: 'Mariana Silva (Jefa de Planta Miraflores)',
    reportedBy: 'Mateo Quispe',
    reportedRole: 'SUPERVISOR',
    createdAt: '2026-09-29 11:15',
    internalNotes: [
      {
        id: 'NOT-01',
        author: 'Mariana Silva',
        text: 'Se contactó a la cliente Luciana Barandiarán a las 11:40 am para informarle sobre la condición previa de la prenda. Se aguarda confirmación para prueba en parche oculto.',
        createdAt: '2026-09-29 11:45',
      },
    ],
  },
  {
    id: 'INC-0185',
    orderId: 'SOL-4560',
    customerId: 'CUST-006',
    customerName: 'Sofía Montalvo Cisneros',
    type: 'RETRASO_OPERACIONAL',
    severity: 'MEDIA',
    status: 'OPEN',
    description:
      'Retraso de más de 45 minutos en la asignación de chofer para recogida en zona San Isidro debido a alta congestión en hora punta.',
    evidences: [],
    assignedTo: 'Elena Rostova (Supervisor)',
    reportedBy: 'Sistema LaundryWeb',
    reportedRole: 'ADMIN',
    createdAt: '2026-09-29 14:05',
    internalNotes: [
      {
        id: 'NOT-02',
        author: 'Elena Rostova',
        text: 'Se intentará reasignar a Lucía Santillán o chofer de Sede Norte.',
        createdAt: '2026-09-29 14:10',
      },
    ],
  },
  {
    id: 'INC-0180',
    orderId: 'SOL-4552',
    customerId: 'CUST-001',
    customerName: 'María Torres Alarcón',
    type: 'CLIENTE_AUSENTE',
    severity: 'BAJA',
    status: 'RESOLVED',
    description:
      'En el primer intento de recogida el cliente no respondía al intercomunicador. Se reprogramó 30 minutos después exitosamente.',
    evidences: [],
    assignedTo: 'Carlos Ruiz',
    reportedBy: 'Carlos Ruiz',
    reportedRole: 'SUPERVISOR',
    createdAt: '2026-09-26 10:15',
    resolvedAt: '2026-09-26 11:10',
    resolutionNotes:
      'El conserje notificó que la cliente había bajado a compras breves. Recogida efectuada a las 11:10 am.',
    internalNotes: [],
  },
];

export const INITIAL_CATALOG: CatalogItem[] = [
  // Prendas
  {
    id: 'CAT-01',
    name: 'Camisa / Blusa de algodón',
    category: 'PRENDAS',
    type: 'Prenda Individual',
    description:
      'Lavado con agentes protectores de fibra y planchado al vapor vertical.',
    price: 6.5,
    estimatedHours: 24,
    minHours: 12,
    maxHours: 36,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-02',
    name: 'Traje ejecutivo 2 piezas (Saco + Pantalón)',
    category: 'PRENDAS',
    type: 'Conjunto',
    description: 'Dry cleaning ecológico especializado sin olores agresivos.',
    price: 18.0,
    estimatedHours: 36,
    minHours: 24,
    maxHours: 48,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-03',
    name: 'Pantalón de vestir / Jean',
    category: 'PRENDAS',
    type: 'Prenda Individual',
    description:
      'Lavado neutro para preservación de color y planchado de quiebre.',
    price: 8.5,
    estimatedHours: 24,
    minHours: 12,
    maxHours: 36,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-04',
    name: 'Vestido casual / diario',
    category: 'PRENDAS',
    type: 'Prenda Individual',
    description: 'Tratamiento delicado antiarrugas.',
    price: 14.0,
    estimatedHours: 24,
    minHours: 18,
    maxHours: 36,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-05',
    name: 'Vestido de fiesta / seda / pedrería',
    category: 'PRENDAS',
    type: 'Alta Costura',
    description:
      'Inspección manual con luz ultravioleta y solventes de origen botánico.',
    price: 28.0,
    estimatedHours: 48,
    minHours: 36,
    maxHours: 72,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-06',
    name: 'Abrigo de lana / Paño grueso',
    category: 'PRENDAS',
    type: 'Prenda Pesada',
    description: 'Limpieza profesional con acabado cepillado de fibra.',
    price: 26.0,
    estimatedHours: 48,
    minHours: 36,
    maxHours: 72,
    status: 'ACTIVE',
  },

  // Servicios
  {
    id: 'CAT-11',
    name: 'Lavado por Kilos (Bolsa Fresh 5kg)',
    category: 'SERVICIOS',
    type: 'Carga por Peso',
    description:
      'Ropa diaria separada por claros y oscuros, lavado suave y doblado premium.',
    price: 18.0,
    estimatedHours: 24,
    minHours: 12,
    maxHours: 36,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-12',
    name: 'Lavado por Kilos (Bolsa Fresh 10kg)',
    category: 'SERVICIOS',
    type: 'Carga por Peso',
    description:
      'Ideal para familias. Incluye suavizante aromaterapia hipoalergénico.',
    price: 32.0,
    estimatedHours: 24,
    minHours: 18,
    maxHours: 36,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-13',
    name: 'Sanitización Hospitalaria e Industrial',
    category: 'SERVICIOS',
    type: 'B2B Termodesinfección',
    description:
      'Protocolo de lavado a 85°C con peróxido e inyección de ozono.',
    price: 0.95,
    estimatedHours: 16,
    minHours: 8,
    maxHours: 24,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-14',
    name: 'Edredón / Plumón King Size',
    category: 'SERVICIOS',
    type: 'Ropa de Hogar',
    description:
      'Desinfección profunda antiácaros y secado rotativo esponjoso.',
    price: 26.0,
    estimatedHours: 36,
    minHours: 24,
    maxHours: 48,
    status: 'ACTIVE',
  },

  // Extras
  {
    id: 'CAT-21',
    name: 'Almidonado fino en cuellos y puños',
    category: 'EXTRAS',
    type: 'Acabado',
    description:
      'Estructura nítida profesional para presentaciones ejecutivas.',
    price: 3.5,
    estimatedHours: 0,
    minHours: 0,
    maxHours: 0,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-22',
    name: 'Bolsa protectora biodegradable hermética',
    category: 'EXTRAS',
    type: 'Empaque Eco',
    description:
      'Material derivado de fécula de maíz con cierre Zip reutilizable.',
    price: 2.0,
    estimatedHours: 0,
    minHours: 0,
    maxHours: 0,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-23',
    name: 'Tratamiento antimanchas hidrofóbico Nanotech',
    category: 'EXTRAS',
    type: 'Protección',
    description:
      'Crea una película invisible repelente a líquidos en sacos y vestidos.',
    price: 9.0,
    estimatedHours: 4,
    minHours: 2,
    maxHours: 6,
    status: 'ACTIVE',
  },
  {
    id: 'CAT-24',
    name: 'Percha de madera natural con antideslizante',
    category: 'EXTRAS',
    type: 'Accesorio',
    description:
      'Conserva la silueta del hombro de trajes y abrigos sin deformar.',
    price: 4.5,
    estimatedHours: 0,
    minHours: 0,
    maxHours: 0,
    status: 'ACTIVE',
  },
];

export const INITIAL_PROMOTIONS: Promotion[] = [
  {
    id: 'PROM-01',
    name: 'Bienvenida Clean & Fresh',
    code: 'FRESHSTART',
    description: '15% de descuento en el primer pedido para usuarios nuevos.',
    discountType: 'PERCENTAGE',
    discountValue: 15,
    minOrderAmount: 25.0,
    usageLimit: 500,
    usageCount: 142,
    applicableServices: ['Todos los servicios'],
    startDate: '2026-01-01',
    endDate: '2026-12-31',
    status: 'ACTIVE',
  },
  {
    id: 'PROM-02',
    name: 'Edredones Impecables Otoño',
    code: 'EDREDON20',
    description:
      'Descuento de $8.00 fijos en lavado de edredones y ropa de cama pesada.',
    discountType: 'FIXED',
    discountValue: 8.0,
    minOrderAmount: 40.0,
    usageLimit: 200,
    usageCount: 88,
    applicableServices: ['Edredón / Plumón King Size', 'Ropa de Hogar'],
    startDate: '2026-09-01',
    endDate: '2026-10-31',
    status: 'ACTIVE',
  },
  {
    id: 'PROM-03',
    name: 'Corporativo San Isidro Express',
    code: 'CORPEXEC25',
    description:
      '25% de descuento en trajes y camisas ejecutivas para empresas aliadas.',
    discountType: 'PERCENTAGE',
    discountValue: 25,
    minOrderAmount: 60.0,
    usageLimit: 100,
    usageCount: 39,
    applicableServices: [
      'Traje ejecutivo 2 piezas',
      'Camisa / Blusa de algodón',
    ],
    startDate: '2026-08-15',
    endDate: '2026-11-30',
    status: 'ACTIVE',
  },
  {
    id: 'PROM-04',
    name: 'Verano Fresh 2026 (Programada)',
    code: 'VERANO2026',
    description: 'Promoción especial para vestidos ligeros y prendas de playa.',
    discountType: 'PERCENTAGE',
    discountValue: 20,
    minOrderAmount: 30.0,
    usageLimit: 300,
    usageCount: 0,
    applicableServices: ['Vestido casual / diario'],
    startDate: '2026-12-01',
    endDate: '2027-02-28',
    status: 'SCHEDULED',
  },
];

export const INITIAL_REWARDS: Reward[] = [
  {
    id: 'REW-01',
    name: 'Lavado de Edredón King Size Gratis',
    description:
      'Canjeable por 1 servicio completo de edredón con desinfección antiácaros.',
    pointsCost: 800,
    minPurchases: 3,
    minSpend: 100,
    validityDays: 90,
    status: 'ACTIVE',
  },
  {
    id: 'REW-02',
    name: 'Bolsa Fresh 5kg Sin Costo',
    description:
      'Lavado y doblado de una bolsa de 5kg de prendas de uso diario.',
    pointsCost: 500,
    minPurchases: 2,
    minSpend: 50,
    validityDays: 60,
    status: 'ACTIVE',
  },
  {
    id: 'REW-03',
    name: 'Crédito de Billetera Digital $20',
    description:
      'Saldo directo aplicable a cualquier orden futura sin fecha de vencimiento.',
    pointsCost: 1200,
    minPurchases: 5,
    minSpend: 180,
    validityDays: 180,
    status: 'ACTIVE',
  },
  {
    id: 'REW-04',
    name: 'Kit de Cuidado Textil Ecológico',
    description:
      'Incluye 2 bolas de lana natural para secadora y perfume botánico de lavanda.',
    pointsCost: 650,
    minPurchases: 1,
    minSpend: 40,
    validityDays: 45,
    status: 'ACTIVE',
  },
];

export const INITIAL_REDEMPTIONS: RewardRedemption[] = [
  {
    id: 'RED-01',
    customerId: 'CUST-001',
    customerName: 'María Torres Alarcón',
    rewardId: 'REW-02',
    rewardName: 'Bolsa Fresh 5kg Sin Costo',
    pointsSpent: 500,
    date: '2026-09-24 16:30',
    status: 'DELIVERED',
    reviewedBy: 'Carlos Mendoza',
    notes: 'Aplicado en solicitud SOL-4552 con éxito.',
  },
  {
    id: 'RED-02',
    customerId: 'CUST-004',
    customerName: 'Luciana Barandiarán',
    rewardId: 'REW-04',
    rewardName: 'Kit de Cuidado Textil Ecológico',
    pointsSpent: 650,
    date: '2026-09-28 11:20',
    status: 'PENDING',
    notes: 'Pendiente de entrega con el próximo pedido.',
  },
  {
    id: 'RED-03',
    customerId: 'CUST-007',
    customerName: 'Hotel Boutique Casa Andina Fresh',
    rewardId: 'REW-03',
    rewardName: 'Crédito de Billetera Digital $20',
    pointsSpent: 1200,
    date: '2026-09-29 08:15',
    status: 'APPROVED',
    reviewedBy: 'Carlos Mendoza',
    notes: 'Acreditado a la cuenta corriente del hotel.',
  },
];

export const INITIAL_POINTS_LEDGER: PointsLedgerEntry[] = [
  {
    id: 'LED-01',
    customerId: 'CUST-001',
    points: 250,
    type: 'PURCHASE',
    reason: 'Acumulación por orden SOL-4552 ($25)',
    date: '2026-09-27 17:05',
  },
  {
    id: 'LED-02',
    customerId: 'CUST-001',
    points: -500,
    type: 'REDEMPTION',
    reason: 'Canje de recompensa: Bolsa Fresh 5kg',
    date: '2026-09-24 16:30',
  },
  {
    id: 'LED-03',
    customerId: 'CUST-001',
    points: 100,
    type: 'ADMIN_ADJUSTMENT',
    reason: 'Bonificación por fidelidad primer mes',
    date: '2026-09-15 11:00',
    adminUser: 'Carlos Mendoza',
  },
  {
    id: 'LED-04',
    customerId: 'CUST-004',
    points: 450,
    type: 'PURCHASE',
    reason: 'Acumulación por orden SOL-4568 ($45)',
    date: '2026-09-20 14:10',
  },
  {
    id: 'LED-05',
    customerId: 'CUST-004',
    points: -650,
    type: 'REDEMPTION',
    reason: 'Canje: Kit de Cuidado Textil',
    date: '2026-09-28 11:20',
  },
  {
    id: 'LED-06',
    customerId: 'CUST-007',
    points: 2800,
    type: 'PURCHASE',
    reason: 'Acumulación orden hotelera corporativa',
    date: '2026-09-25 18:30',
  },
  {
    id: 'LED-07',
    customerId: 'CUST-007',
    points: -1200,
    type: 'REDEMPTION',
    reason: 'Canje de crédito en billetera $20',
    date: '2026-09-29 08:15',
    adminUser: 'Carlos Mendoza',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'AUD-01',
    timestamp: 'Hoy 14:16',
    userName: 'Sistema LaundryWeb',
    userRole: 'ADMIN',
    action: 'SOLICITUD_CREADA',
    entity: 'Order',
    entityId: 'SOL-4587',
    previousValue: '-',
    newValue: 'PICKUP_PENDING',
    notes: 'Nueva orden generada por María Torres',
  },
  {
    id: 'AUD-02',
    timestamp: 'Hoy 14:05',
    userName: 'Elena Rostova',
    userRole: 'SUPERVISOR',
    action: 'CHOFER_ASIGNADO',
    entity: 'Order',
    entityId: 'SOL-4586',
    previousValue: 'Sin asignar',
    newValue: 'Javier Arriola (MOT-442)',
    notes: 'Asignación manual de chofer',
  },
  {
    id: 'AUD-03',
    timestamp: 'Hoy 11:15',
    userName: 'Mariana Silva',
    userRole: 'SUPERVISOR',
    action: 'ESTADO_CAMBIADO',
    entity: 'Order',
    entityId: 'SOL-4579',
    previousValue: 'AT_FACILITY',
    newValue: 'QUARANTINE',
    notes: 'Mancha persistente detectada en orla de vestido',
  },
  {
    id: 'AUD-04',
    timestamp: 'Hoy 09:15',
    userName: 'Andrés Villalobos',
    userRole: 'ADMIN',
    action: 'KYC_DOCUMENTO_SUBIDO',
    entity: 'Customer',
    entityId: 'CUST-003',
    previousValue: 'Sin documentos',
    newValue: 'DNI + Selfie subidos',
    notes: 'Solicitud de verificación pendiente',
  },
  {
    id: 'AUD-05',
    timestamp: 'Ayer 17:15',
    userName: 'Carlos Mendoza',
    userRole: 'ADMIN',
    action: 'KYC_RECHAZADO',
    entity: 'Customer',
    entityId: 'CUST-005',
    previousValue: 'PENDING',
    newValue: 'REJECTED',
    notes: 'Documento borroso y bordes recortados',
  },
];

prepareWebDemoData(
  {
    orders: INITIAL_ORDERS,
    customers: INITIAL_CUSTOMERS,
    drivers: INITIAL_DRIVERS,
    facilities: INITIAL_FACILITIES,
    settings: INITIAL_SETTINGS,
  },
  true,
);

export const INITIAL_FULFILLMENT_SCENARIOS = [
  {
    id: 'SOL-STORE-001',
    mode: 'HOME_STORE',
    facilityId: 'FAC-02',
    customerId: 'CUST-001',
    handoffs: [
      { id: 'HND-SOL-STORE-001-1', type: 'CUSTOMER_TO_DRIVER', code: '583214' },
      {
        id: 'HND-SOL-STORE-001-2',
        type: 'FACILITY_TO_CUSTOMER',
        code: '583351',
      },
    ],
  },
  {
    id: 'SOL-HOME-001',
    mode: 'HOME_HOME',
    facilityId: 'FAC-02',
    customerId: 'CUST-001',
    pickupAssignmentId: 'SOL-HOME-001-pickup',
    deliveryAssignmentId: 'SOL-HOME-001-delivery',
    handoffs: [
      { id: 'HND-SOL-HOME-001-1', type: 'CUSTOMER_TO_DRIVER', code: '726483' },
      { id: 'HND-SOL-HOME-001-2', type: 'DRIVER_TO_FACILITY', code: '726620' },
      { id: 'HND-SOL-HOME-001-3', type: 'FACILITY_TO_DRIVER', code: '726757' },
      { id: 'HND-SOL-HOME-001-4', type: 'DRIVER_TO_CUSTOMER', code: '726894' },
    ],
  },
] as const;
