const {test,expect}=require('@playwright/test');
test('Expo app renders local fixtures, weight QR and four-mode wizard without generic pictures',async({page})=>{
  const errors=[];page.on('pageerror',e=>errors.push(e.message));
  await page.setViewportSize({width:430,height:932});
  await page.goto('http://127.0.0.1:8083');
  await page.getByText('Cliente demo',{exact:true}).click();
  await page.getByText('Entrar',{exact:true}).click();
  await expect(page.getByText('Tu próxima acción',{exact:true})).toBeVisible({timeout:30000});
  await page.getByRole('tab',{name:/Pedidos/}).click();
  await page.getByText('SOL-WEIGHT-001',{exact:true}).click();
  await expect(page.getByText('Importe pendiente de pesaje · PENDING_AMOUNT',{exact:true})).toBeVisible();
  await expect(page.getByText('Presenta este código.',{exact:false})).toBeVisible();
  await expect(page.locator('svg')).not.toHaveCount(0);
  await page.getByText('Volver',{exact:true}).count().then(async count=>{if(count)await page.getByText('Volver',{exact:true}).click();else await page.goBack();});
  await page.getByRole('button',{name:'Nueva solicitud',exact:true}).click();
  await expect(page.getByText('Modelo del servicio',{exact:true})).toBeVisible();
  expect(errors).toEqual([]);
});

const visible=(page,text)=>page.getByText(text,{exact:true}).filter({visible:true});
const appState=page=>page.evaluate(()=>JSON.parse(localStorage.getItem('laundry_app_business_v3')));
async function loginDemo(page,role){await visible(page,role+' demo').click();await visible(page,'Entrar').click();}
async function returnAndLogout(page,role){await page.getByRole('button',{name:'Volver',exact:true}).click();if(role==='client')await page.getByRole('tab',{name:/Perfil/}).click();await visible(page,role==='client'?'Cerrar sesión':'Cerrar sesión / cambiar cuenta').click();await expect(visible(page,'Entrar')).toBeVisible();}
test('Expo store flow completes across operator and client sessions with persistent weight, approval and custody',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.setViewportSize({width:430,height:932});await page.goto('/');await loginDemo(page,'Administrador');await visible(page,'SOL-WEIGHT-001').click();
  let state=await appState(page);const handoff=state.handoffs.find(h=>h.orderId==='SOL-WEIGHT-001'&&h.type==='CUSTOMER_TO_FACILITY'&&h.status==='ACTIVE');await page.getByLabel('Código de transferencia').fill(handoff.fallbackCode);await page.getByRole('button',{name:'Verificar código',exact:true}).click();await page.getByLabel('Cantidad recibida').fill(String(state.orders.find(o=>o.id==='SOL-WEIGHT-001').itemCount));await page.getByRole('button',{name:'Confirmar entrega física',exact:true}).click();
  await page.getByLabel('Peso recibido').fill('22.5');await page.getByRole('button',{name:'Registrar peso LB',exact:true}).click();await page.getByPlaceholder('Mensaje visible para el cliente').fill('Tratamiento adicional solicitado.');await page.getByRole('button',{name:'Confirmar inspección',exact:true}).click();await page.getByPlaceholder('Importe de ajuste',{exact:true}).fill('5');await page.getByPlaceholder('Motivo interno del ajuste o resolución').fill('Detalle interno reservado.');await page.getByRole('button',{name:'Proponer ajuste al cliente',exact:true}).click();
  await returnAndLogout(page,'admin');await loginDemo(page,'Cliente');await page.getByRole('tab',{name:/Pedidos/}).click();await visible(page,'SOL-WEIGHT-001').click();await page.getByRole('button',{name:'Aceptar ajuste',exact:true}).click();await page.getByRole('button',{name:'Pagar con tarjeta · Demo',exact:true}).click();await expect.poll(async()=>{const state=await appState(page);return state.orders.find(o=>o.id==='SOL-WEIGHT-001').pricing.paymentStatus;}).toBe('PAID');await returnAndLogout(page,'client');
  await loginDemo(page,'Administrador');await visible(page,'SOL-WEIGHT-001').click();for(const label of ['Iniciar procesamiento','Pasar a control de calidad','Marcar listo'])await page.getByRole('button',{name:label,exact:true}).click();state=await appState(page);const release=state.handoffs.find(h=>h.orderId==='SOL-WEIGHT-001'&&h.type==='FACILITY_TO_CUSTOMER'&&h.status==='ACTIVE');await page.getByLabel('Código de transferencia').fill(release.fallbackCode);await page.getByRole('button',{name:'Verificar código',exact:true}).click();await page.getByLabel('Nombre del receptor').fill('Titular del pedido');await page.getByLabel('Relación o autorización del receptor').fill('Titular');await page.getByRole('button',{name:'Confirmar entrega física',exact:true}).click();await expect.poll(async()=>(await appState(page)).orders.find(o=>o.id==='SOL-WEIGHT-001').status).toBe('COMPLETED');await page.reload();await expect.poll(async()=>{const s=await appState(page),o=s.orders.find(o=>o.id==='SOL-WEIGHT-001');return {status:o.status,weight:o.pricing.measuredWeight,paid:o.pricing.amountPaid,points:s.pointsLedger.filter(p=>p.orderId===o.id&&p.type==='PURCHASE').length};}).toEqual({status:'COMPLETED',weight:22.5,paid:41,points:1});expect(errors).toEqual([]);
});
test('Expo five-step fixed checkout creates one store order with an exact quote and a single reservation',async({page})=>{
  const errors=[];page.on('pageerror',error=>errors.push(error.message));await page.setViewportSize({width:430,height:932});await page.goto('/');await loginDemo(page,'Cliente');await visible(page,'Nueva solicitud').click();await visible(page,'Agregar prenda').click();await visible(page,'Agregar').click();await visible(page,'Continuar').click();await visible(page,'Continuar').click();await visible(page,'Ingreso y retiro en sede').click();await page.getByText(/^\d{4}-\d{2}-\d{2} · /).filter({visible:true}).first().click();await visible(page,'Continuar').click();await visible(page,'Continuar').click();await expect(visible(page,'Total: $5.00')).toBeVisible();const before=(await appState(page)).orders.map(o=>o.id);await page.getByRole('button',{name:'Confirmar y pagar · Demo',exact:true}).click();await expect(page.getByRole('button',{name:'Ver mapa del pedido',exact:true})).toBeVisible();const state=await appState(page),created=state.orders.filter(o=>!before.includes(o.id));expect(created).toHaveLength(1);expect(created[0].fulfillment.mode).toBe('STORE_STORE');expect(created[0].pricing.paymentStatus).toBe('PAID');expect(created[0].pricing.total).toBe(5);expect(state.reservations.filter(r=>r.orderId===created[0].id&&r.active)).toHaveLength(1);await page.getByRole('button',{name:'Ver mapa del pedido',exact:true}).click();await expect(visible(page,'Cómo llegar a la sede')).toBeVisible();expect(errors).toEqual([]);
});
